### ISSUE TITLE
如何保存训练后的权重

### ISSUE THREAD

**Issue by kyleliaokai** [OleehyO/TexTeller#19]
作者您好，当我训练自己的时候的时候，能够训练python -m models.tokenizer.train 并保存了自己的tokenizer
当我通过python -m models.ocr_model.train.train，并未添加您训练好的模型，是通过您给的一些数据集进行训练
训练后不知道应该如何保存成作者您huggingface上这样的权重：https://huggingface.co/OleehyO/TexTeller/tree/main。
我想将保存下来的权重后加载您写的web进行重复使用
请问我是需要添加怎样的操作才能做到你这样吗？

**Comment by OleehyO** [comment]
训练完了以后会有一个目录保存训练结果，这个目录可以在[training_args.py](https://github.com/OleehyO/TexTeller/blob/main/src/models/ocr_model/train/training_args.py)里进行配置（output_dir）。

训练完了以后在[start_web.sh](https://github.com/OleehyO/TexTeller/blob/main/src/start_web.sh)里面把`CHECKPOINT_DIR`改为那个目录即可。

**Comment by kyleliaokai** [comment]
<img width="740" alt="image" src="https://github.com/OleehyO/TexTeller/assets/108382167/f6a31dd0-f9e4-4580-8f5a-c4fa391cace3">
这是修改training_args.py 的位置，运行python -m models.ocr_model.train.train 后得到一个src/models/ocr_model/train/train_result/runs/Apr23_14-11-12_autodl-container-48ad40b954-dbcebda1 目录，将这个目录放入CHECKPOINT_DIR改为那个目录，无法运行。好像训练过程中没有保存什么权重结果

**Comment by kyleliaokai** [comment]
感谢作者，耐心的解答
