### ISSUE TITLE
ImportError: cannot import name 'img_transform_fn' from 'models.ocr_model.utils.functional'

### ISSUE THREAD

**Issue by KiLJ4EdeN** [OleehyO/TexTeller#28]
There is no such function in the functional module of utils
i swapped it to img_inf_transform and training works, wanted to see if this is right

**Comment by OleehyO** [comment]
My bad, it's fixed now. Just make sure to use the latest version.

**Comment by KiLJ4EdeN** [comment]
> My bad, it's fixed now. Just make sure to use the latest version.

Will do
Thanks for the great work.
