### ISSUE TITLE
When running the training script, the following error is reported. How to solve it?

### ISSUE THREAD

**Issue by pjpanadas** [OleehyO/TexTeller#30]
![1](https://github.com/OleehyO/TexTeller/assets/43002940/74e74caa-6737-490b-8cd6-1a4a6648e472)
ValueError: invalid literal for int() with base 10: 'lhy_custom'

**Comment by OleehyO** [comment]
My bad, it's fixed now. Just make sure to use the latest version. 

Also, reinstall and [reconfigure your environment](https://github.com/OleehyO/TexTeller?tab=readme-ov-file#-getting-started) from scratch since it's been updated to make sure everything works right.
