### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ALIOSKUPER** [OleehyO/TexTeller#63]
使用pycharm，在对分词器或者texteller训练的时候就会出现这个错误，但是在脚本import模块组件那通过ctrl+左键可以直接进入到对应的模型，以及可以进入对应的函数或类。
希望能得到您的帮助

**Comment by OleehyO** [comment]
因为使用了相对导入，所以需要在`src/`目录下运行脚本，并使用`-m`选项。

**Comment by ALIOSKUPER** [comment]
您说的那样是可以的！！！ 为了在pycharm中进行调试，我参考了这个链接 改成可以在pycharm进行同样效果的运行https://blog.csdn.net/qq_39852676/article/details/107856620， 
![Uploading image.png…]()
