### ISSUE TITLE
gpu 训练报错 return torch._C._broadcast_coalesced(tensors, devices, buffer_size) RuntimeError: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

### ISSUE THREAD

**Issue by ALIOSKUPER** [OleehyO/TexTeller#68]
你好 使用texteller在单gpu上训练的时候，将src/models/ocr_model/train/下的training_arg.py种的‘’use_gpu''改成False的时候，进行训练就会出现上面错误，同时伴随下面这个警告
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

希望得到您的帮助

**Comment by OleehyO** [comment]
建议先检查显卡的驱动版本是否支持cuda12.0以上。如果还是有问题，可以使用提供的[docker镜像](https://hub.docker.com/r/oleehyo/texteller)来解决环境的问题。

**Comment by ALIOSKUPER** [comment]
您好  感谢您的回复~  查看cuda 是12.4的 没有正常运行的原因在现在的服务器中需要在每次运行之前需要添加环境变量 （参考链接 ：https://blog.csdn.net/m0_37426155/article/details/108129952  的篇章三 ） 并且将环境变量连到指定的python环境下   export LD_LIBRARY_PATH=‘python运行环境绝对路径’/lib:$LD_LIBRARY_PATH  在运行代码 希望对您有所帮助
