### ISSUE TITLE
How to accelerate model inference？

### ISSUE THREAD

**Issue by gk966988** [OleehyO/TexTeller#76]
How to accelerate model inference and  is thres some ideal?

**Comment by ZZzero0O** [comment]
你好，NVIDIA rtx 4090 ， img size 594*219, inference time:1s
请问你的设备是什么样的，我的推理时间和你的差不多吗，还是参数设置有问题

**Comment by ZZzero0O** [comment]
hello！NVIDIA RTX 4090、561*219 img size, inference time: 1s
可以参考下你的设备信息和参数吗，我的是不是参数设置失误导致推理速度慢
